<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
    <DefaultItemExcludes>$(DefaultItemExcludes);Nova3D\**;templates\**;artifacts\**</DefaultItemExcludes>
    <EnableMGCBItems>false</EnableMGCBItems>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.4.1" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.4.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="Nova3D\Nova3D.csproj" />
  </ItemGroup>

  <ItemGroup>
    <MonoGameContentReference Include="Content\Content.mgcb" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Config\nova3d.json" CopyToOutputDirectory="PreserveNewest" />
    <None Update="LocalAssets\Models\**\*.glb" CopyToOutputDirectory="PreserveNewest" />
    <None Update="LocalAssets\Models\**\*.png" CopyToOutputDirectory="PreserveNewest" />
    <None Update="LocalAssets\Models\**\*.jpg" CopyToOutputDirectory="PreserveNewest" />
    <None Update="LocalAssets\Models\**\*.jpeg" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
