<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Nova3D.Physics.Bepu\Nova3D.Physics.Bepu.csproj" />
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.4.1" />
    <Compile Include="..\Shared\SampleMeshFactory.cs" Link="Shared\SampleMeshFactory.cs" />
  </ItemGroup>
</Project>
