<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Nova3D" Version="0.1.0" />
    <!--#if (physics)-->
    <PackageReference Include="Nova3D.Physics.Bepu" Version="0.1.0" />
    <!--#endif-->
    <!--#if (ui)-->
    <PackageReference Include="Nova3D.UI.Gum" Version="0.1.0" />
    <!--#endif-->
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.4.1" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.4.1" />
  </ItemGroup>

  <ItemGroup>
    <MonoGameContentReference Include="Content\Content.mgcb" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\**\*" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Shaders\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
